name: Build Cosmix Plugin

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Generate
        run: |
          ./gradlew AnimeDekhoProvider:makeCsx
          ./gradlew makePluginsJson
          cp AnimeDekhoProvider/build/AnimeDekhoProvider.csx build/
          cp AnimeDekhoProvider/build/AnimeDekhoProvider.jar build/

      - name: Deploy to builds branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds
          folder: build
          clean: false
          token: ${{ secrets.GITHUB_TOKEN }}
